# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee6b233d63b29cd96d1a0839f2a1801b249e7a404482643b7b0d71af4100f3578233bcf661da4b573d83155c4953ecdd4d95d762edb99273de237fad2b0a0b7

test:
  secret_key_base: 6c7642d78f22b98803c3dc6f6aec5c4a4ddca017588b90b049bc2932de847fe8b629bee613f3d58403a0bf49408e2bd816d0390f76dd86883e617b5db877ed98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
